[aerosol]
bc_layer_width_levels = 4 # The black carbon layer width expressed in levels (1 level ≙ 0.5km), must be >= 2
bc_layer_distribution = "gaussian" # The distribution in the black carbon layer, either "guassian" or "uniform"
bc_mass = 50.0e12 # Black carbon mass in g
bc_mass_ext_coeff = 9.0 # Black carbon mass extinction coefficient in m^2/kg
bc_e_folding_time = 5.5 # Black carbon e-folding time in years
bc_ssa = 0.31 # Black carbon single scattering albedo in the range [0,1] -> 0 purely absorbing, 1 purely scattering